"""update tables

Revision ID: a2c03f8a8a77
Revises: e31beef93767
Create Date: 2025-04-25 12:51:09.085349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c03f8a8a77'
down_revision = 'e31beef93767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('jobs', sa.Column('salary_from', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('salary_to', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('responses', sa.Column('message', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'message')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'salary_to')
    op.drop_column('jobs', 'salary_from')
    op.drop_column('jobs', 'description')
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
